version: "3"

services:

  eosweb:
    container_name: eosweb
    build: .
    ports:
      - 3039:3039
      - 9615:9615
    restart: always
    links:
      - daomongohistory
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      MONGO_URI: ${NODE_MONGO_URI}
      NODE_URI: ${NODE_URI}
      HISTORY_URI: "http://daomongohistory:3333"


  daomongohistory:
    container_name: eosweb_history
    image: mixbytes/dao-mongo-history-api:latest
    ports:
      - 3333:3333
    restart: always
    environment:
      MONGO_URI: ${NODE_MONGO_URI}
      NODE_URI: ${NODE_URI}


